### ISSUE TITLE
Requesting for genmax code

### ISSUE THREAD

**Issue by dhaksha-Jey** [zakimjz/newEclat#1]
Hi sir@zakimjz, Can you please share me the genmax code. thank you

**Comment by zakimjz** [comment]
The code is available at:
http://www.cs.rpi.edu/~zaki/www-new/pmwiki.php/Software/Software#toc9
-zaki

-- 
Mohammed J. Zaki
Phone: 518-279-9614
Email: mjzaki@gmail.com

**Comment by dhaksha-Jey** [comment]
Thank you so much sir. So thankful to you

**Comment by dhaksha-Jey** [comment]
Hi sir, I found some error on running this Genmax code and I'm not clear
about it. I also don't know how to attach the input dataset in this code..
Can you please help me in this sir.. Thank you

**Comment by zakimjz** [comment]
Are you referring to the github code. The files test.ascii and test2.ascii show example input file in the NO OFFSET format. You can run on the example file as follows: ./eclat -itest.ascii -S 1 -a 2 -o -x

**Comment by dhaksha-Jey** [comment]
Greetings Sir,
 As I referred your publications list, Can I please get code for Zigzag
algorithm
